expenses/urls.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.urls import path, reverse_lazy
from .models import Expense, Category
from .views import ExpenseListView, CategoryListView, CategoryUpdateView


urlpatterns = [
    path('expense/list/',
         ExpenseListView.as_view(),
         name='expense-list'),
    path('expense/create/',
         CreateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-create'),
    path('expense/<int:pk>/edit/',
         UpdateView.as_view(
            model=Expense,
            fields='__all__',
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_update.html'
         ),
         name='expense-edit'),
    path('expense/<int:pk>/delete/',
         DeleteView.as_view(
            model=Expense,
            success_url=reverse_lazy('expenses:expense-list'),
            template_name='generic_delete.html'
         ),
         name='expense-delete'),

    path('category/list/',
         CategoryListView.as_view(),
         name='category-list'),
    path('categories/<int:pk>/edit/',
          CategoryUpdateView.as_view(),
          name='category-edit'),
    path('category/create/',
         CreateView.as_view(
            model=Category,
            fields='__all__',
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_update.html'
         ),
         name='category-create'),
    path('category/<int:pk>/delete/',
         DeleteView.as_view(
            model=Category,
            success_url=reverse_lazy('expenses:category-list'),
            template_name='generic_delete.html'
         ),
         name='category-delete'),
]

project/urls.py
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('',
         RedirectView.as_view(pattern_name='expenses:expense-list'),
         name='dashboard'),
    path('expenses/',
         include(('expenses.urls', 'expenses'), namespace='expenses')),
]

expenses/models.py
import datetime
from django.db import models


class Category(models.Model):
    class Meta:
        ordering = ('name',)

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class Expense(models.Model):
    class Meta:
        ordering = ('-date', '-pk')

    category = models.ForeignKey(Category, models.PROTECT, null=True, blank=True)

    name = models.CharField(max_length=50)
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    date = models.DateField(default=datetime.date.today, db_index=True)

    def __str__(self):
        return f'{self.date} {self.name} {self.amount}'

users/models.py
from django.db import models

# Create your models here.

expenses/forms.py
from django import forms
from .models import Expense
from .models import Category


class ExpenseSearchForm(forms.ModelForm):
    start_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date', 'placeholder': 'YYYY-MM-DD'}))
    end_date = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date', 'placeholder': 'YYYY-MM-DD'}))
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all(),required=False,widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Expense
        fields = ('name', 'start_date', 'end_date', 'categories')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].required = False

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

expenses/views.py
from django.views.generic.list import ListView
from django.db.models import Sum, Count
from django.db.models.functions import TruncMonth
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

from .forms import ExpenseSearchForm, CategoryForm
from .models import Expense, Category
from .reports import summary_per_category, total_spent


class ExpenseListView(ListView):
    model = Expense
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        form = ExpenseSearchForm(self.request.GET)
        if form.is_valid():
            name = form.cleaned_data.get('name', '').strip()
            start_date = form.cleaned_data.get('start_date')
            end_date = form.cleaned_data.get('end_date')
            categories = form.cleaned_data.get('categories')

            if name:
                queryset = queryset.filter(name__icontains=name)
            if start_date:
                queryset = queryset.filter(date__gte=start_date)
            if end_date:
                queryset = queryset.filter(date__lte=end_date)
            if categories:
                queryset = queryset.filter(category__in=categories)

        sort_by = self.request.GET.get('sort_by')
        if sort_by:
            queryset = queryset.order_by(sort_by)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        form = ExpenseSearchForm(self.request.GET)
        context['form'] = form
        context['summary_per_category'] = summary_per_category(self.get_queryset())
        context['total_spent'] = total_spent(self.get_queryset())
        queryset = self.get_queryset()
        monthly_summary = (
            queryset
            .annotate(year_month=TruncMonth('date'))
            .values('year_month')
            .annotate(total_amount=Sum('amount'))
            .order_by('year_month')
        )
        context['monthly_summary'] = monthly_summary
        
        return context

class CategoryListView(ListView):
    model = Category
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.annotate(expense_count=Count('expense'))
        return queryset

class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'category_update.html'
    success_url = reverse_lazy('expenses:category-list')

users/views.py
from django.shortcuts import render

# Create your views here.

expenses/templates/expenses/category_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'expenses:category-create' %}">Add category</a>

<table border="1">
    <thead>
        <tr>
            <th>Name</th>
            <th>Expense count</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for obj in object_list %}
        <tr>
            <td>{{ obj.name }}</td>
            <td>{{ obj.expense_count }}</td>
            <td>
                <a href="{% url 'expenses:category-edit' obj.id %}">edit</a>
                <a href="{% url 'expenses:category-delete' obj.id %}">delete</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

expenses/templates/expenses/expense_list.html
{% extends "base.html" %}

{% block content %}

<a href="{% url 'expenses:expense-create' %}">add</a>

<form method="get" action="">
  {{ form.as_p }}
  <label for="sort_by">Sort by:</label>
  <select name="sort_by" id="sort_by">
    <option value="">Select...</option>
    <option value="category">Category (A-Z)</option>
    <option value="-category">Category (Z-A)</option>
    <option value="date">Date (Oldest first)</option>
    <option value="-date">Date (Newest first)</option>
  </select>
  <button type="submit">search</button>
</form>
<br>
<table border="1">
    <caption>Expenses</caption>
    <thead>
      <tr>
        <th>№</th>
        <th>category</th>
        <th>name</th>
        <th>amount</th>
        <th>date</th>
        <th>actions</th>
      </tr>
    </thead>
    <tbody>

    {% for obj in object_list %}
      <tr>
        <td>{{ page_obj.start_index|add:forloop.counter0 }}.</td>
        <td>{{ obj.category|default:"-" }}</td>
        <td>{{ obj.name|default:"-" }}</td>
        <td>{{ obj.amount|floatformat:2 }}</td>
        <td>{{ obj.date }}</td>
        <td>
          <a href="{% url 'expenses:expense-edit' obj.id %}">edit</a>
          <a href="{% url 'expenses:expense-delete' obj.id %}">delete</a>
        </td>
      </tr>
      {% empty %}
      <tr>
        <td colspan="6">no items</td>
      </tr>
    {% endfor %}
    </tbody>
</table>

{% include "_pagination.html" %}
<hr>

<div style="display: flex; gap: 20px;">
  <table border="1">
    <caption>Summary per category</caption>
    <tr>
      {% for category, total in summary_per_category.items %}
      <tr>
          <td>{{ category }}:</td>
          <td>{{ total|floatformat:2 }}</td>
      </tr>
      {% endfor %}
    </tr>
  </table>

  <div style="width: 200px;">
    <table border="1" style="width: 100%;">
      <caption>Total Spent</caption>
      <tr>
        <td>Total:</td>
        <td>{{ total_spent|floatformat:2 }}</td>
      </tr>
    </table>
  </div>
</div>

<hr>

<table border="1">
  <caption>Monthly Summary</caption>
  <thead>
    <tr>
      <th>Year-Month</th>
      <th>Total Amount</th>
    </tr>
  </thead>
  <tbody>
    {% for item in monthly_summary %}
    <tr>
      <td>{{ item.year_month|date:"Y-m" }}</td>
      <td>{{ item.total_amount|floatformat:2 }}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="2">no data</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

project/templates/_pagination.html
<div class="pagination">
    <span class="pagination__nav">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block meta_title %}Expenses app{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  </head>
  <body>
	<a href="{% url 'expenses:expense-list' %}">Expenses</a> | 
	<a href="{% url 'expenses:category-list' %}">Categories</a> | 
	<hr>
    {% block content %}{% endblock %}
  </body>
</html>

project/templates/category_update.html
{% extends "base.html" %}

{% block content %}
<h2>Edit Category</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

project/templates/generic_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Confirm removing "{{object}}"</h1>
<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">delete</button>
</form>

{% endblock %}

project/templates/generic_update.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Save</button>
</form>

{% endblock %}